[2024-04-16T10:35:58.313+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T10:35:58.456+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: priority_one_number_two_dag_v1.generate_random_number scheduled__2024-02-25T00:00:00+00:00 [queued]>
[2024-04-16T10:35:58.537+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: priority_one_number_two_dag_v1.generate_random_number scheduled__2024-02-25T00:00:00+00:00 [queued]>
[2024-04-16T10:35:58.538+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-16T10:35:58.612+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_random_number> on 2024-02-25 00:00:00+00:00
[2024-04-16T10:35:58.656+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=502) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T10:35:58.669+0000] {standard_task_runner.py:63} INFO - Started process 518 to run task
[2024-04-16T10:35:58.715+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'priority_one_number_two_dag_v1', 'generate_random_number', 'scheduled__2024-02-25T00:00:00+00:00', '--job-id', '302', '--raw', '--subdir', 'DAGS_FOLDER/priority_one_number_two_dag.py', '--cfg-path', '/tmp/tmpy1twj5_f']
[2024-04-16T10:35:58.725+0000] {standard_task_runner.py:91} INFO - Job 302: Subtask generate_random_number
[2024-04-16T10:35:58.986+0000] {task_command.py:426} INFO - Running <TaskInstance: priority_one_number_two_dag_v1.generate_random_number scheduled__2024-02-25T00:00:00+00:00 [running]> on host eaff2d74d54d
[2024-04-16T10:35:59.451+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ika' AIRFLOW_CTX_DAG_ID='priority_one_number_two_dag_v1' AIRFLOW_CTX_TASK_ID='generate_random_number' AIRFLOW_CTX_EXECUTION_DATE='2024-02-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-25T00:00:00+00:00'
[2024-04-16T10:35:59.462+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T10:36:00.316+0000] {python.py:237} INFO - Done. Returned value was: [38, 34, 28, 12, 1, 38, 9, 28, 29, 23, 23, 15, 41, 2, 28, 24, 37, 46, 38, 8, 25, 41, 44, 6, 30]
[2024-04-16T10:36:00.365+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T10:36:00.747+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=priority_one_number_two_dag_v1, task_id=generate_random_number, execution_date=20240225T000000, start_date=20240416T103558, end_date=20240416T103600
[2024-04-16T10:36:00.971+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T10:36:01.378+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-16T10:36:01.526+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
