[2024-04-16T10:25:18.695+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T10:25:19.208+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: priority_one_number_one_dag_v1.task_3 scheduled__2024-04-12T00:00:00+00:00 [queued]>
[2024-04-16T10:25:19.283+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: priority_one_number_one_dag_v1.task_3 scheduled__2024-04-12T00:00:00+00:00 [queued]>
[2024-04-16T10:25:19.291+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 6
[2024-04-16T10:25:19.372+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): task_3> on 2024-04-12 00:00:00+00:00
[2024-04-16T10:25:19.411+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=202) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T10:25:19.415+0000] {standard_task_runner.py:63} INFO - Started process 212 to run task
[2024-04-16T10:25:19.437+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'priority_one_number_one_dag_v1', 'task_3', 'scheduled__2024-04-12T00:00:00+00:00', '--job-id', '233', '--raw', '--subdir', 'DAGS_FOLDER/priority_one_number_one_dag.py', '--cfg-path', '/tmp/tmpvo5cjviz']
[2024-04-16T10:25:19.462+0000] {standard_task_runner.py:91} INFO - Job 233: Subtask task_3
[2024-04-16T10:25:19.641+0000] {task_command.py:426} INFO - Running <TaskInstance: priority_one_number_one_dag_v1.task_3 scheduled__2024-04-12T00:00:00+00:00 [running]> on host eaff2d74d54d
[2024-04-16T10:25:20.632+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ika' AIRFLOW_CTX_DAG_ID='priority_one_number_one_dag_v1' AIRFLOW_CTX_TASK_ID='task_3' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-12T00:00:00+00:00'
[2024-04-16T10:25:20.647+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T10:25:21.276+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-16T10:25:21.335+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir -p our_works']
[2024-04-16T10:25:21.460+0000] {subprocess.py:86} INFO - Output:
[2024-04-16T10:25:21.483+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-16T10:25:21.501+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T10:25:21.800+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=priority_one_number_one_dag_v1, task_id=task_3, execution_date=20240412T000000, start_date=20240416T102519, end_date=20240416T102521
[2024-04-16T10:25:22.011+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T10:25:22.505+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-16T10:25:22.520+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
