[2024-04-16T10:30:55.601+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T10:30:55.776+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: priority_one_number_one_dag_v1.task_5 scheduled__2024-04-08T00:00:00+00:00 [queued]>
[2024-04-16T10:30:55.816+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: priority_one_number_one_dag_v1.task_5 scheduled__2024-04-08T00:00:00+00:00 [queued]>
[2024-04-16T10:30:55.817+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 6
[2024-04-16T10:30:55.886+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): task_5> on 2024-04-08 00:00:00+00:00
[2024-04-16T10:30:55.916+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=379) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T10:30:55.925+0000] {standard_task_runner.py:63} INFO - Started process 387 to run task
[2024-04-16T10:30:55.943+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'priority_one_number_one_dag_v1', 'task_5', 'scheduled__2024-04-08T00:00:00+00:00', '--job-id', '272', '--raw', '--subdir', 'DAGS_FOLDER/priority_one_number_one_dag.py', '--cfg-path', '/tmp/tmphlqza1l5']
[2024-04-16T10:30:55.956+0000] {standard_task_runner.py:91} INFO - Job 272: Subtask task_5
[2024-04-16T10:30:56.207+0000] {task_command.py:426} INFO - Running <TaskInstance: priority_one_number_one_dag_v1.task_5 scheduled__2024-04-08T00:00:00+00:00 [running]> on host eaff2d74d54d
[2024-04-16T10:31:17.019+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 272 for task task_5 ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 387)
[2024-04-16T10:31:22.323+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-16T10:31:22.636+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T10:31:22.674+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
