[2024-04-16T10:21:51.672+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T10:21:51.896+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: priority_one_number_one_dag_v1.task_3 scheduled__2024-04-09T00:00:00+00:00 [queued]>
[2024-04-16T10:21:51.957+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: priority_one_number_one_dag_v1.task_3 scheduled__2024-04-09T00:00:00+00:00 [queued]>
[2024-04-16T10:21:51.963+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-16T10:21:52.054+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): task_3> on 2024-04-09 00:00:00+00:00
[2024-04-16T10:21:52.121+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=95) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T10:21:52.150+0000] {standard_task_runner.py:63} INFO - Started process 99 to run task
[2024-04-16T10:21:52.128+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'priority_one_number_one_dag_v1', 'task_3', 'scheduled__2024-04-09T00:00:00+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/priority_one_number_one_dag.py', '--cfg-path', '/tmp/tmp5veav23n']
[2024-04-16T10:21:52.198+0000] {standard_task_runner.py:91} INFO - Job 210: Subtask task_3
[2024-04-16T10:21:53.039+0000] {task_command.py:426} INFO - Running <TaskInstance: priority_one_number_one_dag_v1.task_3 scheduled__2024-04-09T00:00:00+00:00 [running]> on host eaff2d74d54d
[2024-04-16T10:21:53.572+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ika' AIRFLOW_CTX_DAG_ID='priority_one_number_one_dag_v1' AIRFLOW_CTX_TASK_ID='task_3' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-09T00:00:00+00:00'
[2024-04-16T10:21:53.589+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T10:21:53.726+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-16T10:21:53.733+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir -p our_works']
[2024-04-16T10:21:53.820+0000] {subprocess.py:86} INFO - Output:
[2024-04-16T10:21:53.842+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-16T10:21:53.858+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T10:21:54.226+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=priority_one_number_one_dag_v1, task_id=task_3, execution_date=20240409T000000, start_date=20240416T102151, end_date=20240416T102154
[2024-04-16T10:21:54.664+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T10:21:55.889+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T10:21:56.144+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
