[2024-04-16T10:37:25.494+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T10:37:25.644+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: priority_one_number_two_dag_v1.generate_random_number scheduled__2024-03-16T00:00:00+00:00 [queued]>
[2024-04-16T10:37:25.676+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: priority_one_number_two_dag_v1.generate_random_number scheduled__2024-03-16T00:00:00+00:00 [queued]>
[2024-04-16T10:37:25.683+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-16T10:37:25.745+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_random_number> on 2024-03-16 00:00:00+00:00
[2024-04-16T10:37:25.791+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=596) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T10:37:25.809+0000] {standard_task_runner.py:63} INFO - Started process 600 to run task
[2024-04-16T10:37:25.821+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'priority_one_number_two_dag_v1', 'generate_random_number', 'scheduled__2024-03-16T00:00:00+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/priority_one_number_two_dag.py', '--cfg-path', '/tmp/tmpz5hro74k']
[2024-04-16T10:37:25.831+0000] {standard_task_runner.py:91} INFO - Job 335: Subtask generate_random_number
[2024-04-16T10:37:26.417+0000] {task_command.py:426} INFO - Running <TaskInstance: priority_one_number_two_dag_v1.generate_random_number scheduled__2024-03-16T00:00:00+00:00 [running]> on host eaff2d74d54d
[2024-04-16T10:37:27.167+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ika' AIRFLOW_CTX_DAG_ID='priority_one_number_two_dag_v1' AIRFLOW_CTX_TASK_ID='generate_random_number' AIRFLOW_CTX_EXECUTION_DATE='2024-03-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-16T00:00:00+00:00'
[2024-04-16T10:37:27.169+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T10:37:27.463+0000] {python.py:237} INFO - Done. Returned value was: [36, 6, 43, 8, 30, 31, 29, 16, 28, 31, 16, 1, 27, 27, 20, 38, 1, 20, 13, 24, 37, 10, 9, 8, 50]
[2024-04-16T10:37:27.465+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T10:37:27.553+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=priority_one_number_two_dag_v1, task_id=generate_random_number, execution_date=20240316T000000, start_date=20240416T103725, end_date=20240416T103727
[2024-04-16T10:37:27.685+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T10:37:27.777+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-16T10:37:27.800+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
